### ISSUE TITLE
.gitignore is insufficient

### ISSUE THREAD

**Issue by mjlosch** [altMITgcm/MITgcm66h#12]
I find that I need to add "build" and "run" to .gitignore in order to avoid having my screen cluttered with links from the build and run directories in verification after having run ./testreport. Can git differentiate between links and real files? What would be the best syntax for excluding links in .gitignore? I couldn't find anything on the web. 
I have been told that the testreport suite does "in-place-building" or similar and that that's not the best idea, but I don't think we want to go away from that, do we? We could rename all build and run directories into _build and _run, couldn't we?
Is there a better solution?

**Comment by edoddridge** [comment]
It's possible to put `.gitignore` files in subdirectories, so each test directory could get its own with `build` and `run` listed. This should deal with the clutter. 

Changing the directory names would also fix that, but might be more of a pain for users?

I'm not sure about how to exclude links. Will have to look into it.
