### ISSUE TITLE
merging PRs taking too long?

### ISSUE THREAD

**Issue by christophernhill** [altMITgcm/MITgcm66h#9]
@jahn and @jm-c  it feels like merging pull requests may be taking a little long. I can just merge them, but I was thinking you two would do some too! Should we have a target of either merging or sending back for corrections within X hours, on normal working days or something? Right now we have 3 PRs somewhat in limbo - its unclear what their status is.  Maybe this is just because we have things to debug? I don't see any reason not to accept the current PRs? 

@rabernat and @edoddridge whats a good practice for this generally? 

@mjlosch any thoughts? 

I assume we don't want to end up like JPO etc.. and take months/years to publish.

**Comment by rabernat** [comment]
This depends on the complexity and urgency of the PR. Short, simple PRs that fix obvious bugs can likely be merged within hours. (PRs should reference specific "issues" wherever possible.) On the other hand, large and complex PRs can stay open for weeks or even months as the community discusses and provides feedback, and the author iterates and updates the PR. The downside of leaving PRs open for a long time is that they can become stale and require rebasing. But that's better than merging prematurely. 

A good goal would be to review the PRs and provide feedback (via comments and code comments) quickly, rather than a specific target of how quickly they should be merged. 

My PR, for example, is controversial. @edoddridge made some good arguments why pull is better than merge. We can continue to discuss that issue via comments on the PR until we reach a consensus.

**Comment by mjlosch** [comment]
As I already mentioned on the good old devel-list, I find this workflow tedious for the manual (the only thing I tried so far, but I also have to learn the specifics of the rst-language, which makes it even more complicated); in my current view, it will probably lead to less contributions to the manual than now (is that even possible), but without any serious experience with this GitHub, I am in no position to make that claim. I guess it also depends on who will merge or not the PRs. If I (i.e. people like me who now have CVS write permissions) can merge my own PR of actual code, then only the PR from the non-core group would have to wait and undergo specific scrutiny, but that strategy probably beats the purpose of the workflow, doesn't it?
Is the goal to have a workflow that is a similar to what we have now with CVS as possible? Or do you want to use this transition to move to something different, where fewer people are in control (may not be bad). E.g. do you envision to work directly on the main master repo other than just merging pull requests? 
Do I sign this comment or is not part of the Git-lingo? (o:

**Comment by christophernhill** [comment]
@rabernat thanks. 

I do think there is a risk we will end up in how many angels fit on the head of a pin discussions. Human nature, especially in the research world, is to head in that direction in the absence of other constraints. 

I was out yesterday so am not sure what the building 54 15th floor street has to say on this. I will find out later, but I guess I don't see any reason why we haven't merged in all the PRs so far. Doesn't seem like a promising start!

**Comment by christophernhill** [comment]
@mjlosch 
```
Is the goal to have a workflow that is a similar to what we have now with CVS as possible? Or do you want to use this transition to move to something different, where fewer people are in control (may not be bad). E.g. do you envision to work directly on the main master repo other than just merging pull requests?
```
The current thinking is to use PRs for everything. This is slightly different to current CVS process. Its not clear to me that this is going to work, but that is the _right_ thing to do if we can. That is effectively what the Linux kernel does and lots of other projects and it works well for them. Lots of us do use git these days, so I think it can make sense. 

One way to get things unclogged may be to add more committers to the master repo. Even then the model would be to develop in your own repo and then submit a PR (on a branch!) and have someone else accept it. Our hypothesis is that making this transition will make things easier long term, with some short term learning. If that isn't true then we can revert back. 

I did submit a PR myself for something on Tuesday, but then I had to track down Oliver, drag him to Ed's office, explain some things and then finally the PR got merged. If it continues like that I don't think the system is workable, so we will discuss this a bit today and try and see if we can streamline.

**Comment by edoddridge** [comment]
I agree with @rabernat - it's much more important to acknowledge a pull request quickly than to merge it. I'd expect for a project of the size of MITgcm that a pull request would get some attention within a day.

As we transfer fully to GitHub, we will need to establish some working practices for the repo admins to follow. I'd suggest that small, simple, or obvious changes should be merged unilaterally by whichever admin sees it first; if it doesn't require discussion, then just accept it.

As the complexity of the PR increases, then the level of discussion will also increase. This is something the community is going to have to work out. I'd guess that the level of discussion something would have created on the devel list is probably a good guide for the level of discussion the PR should get (but as the newest member of the devel list, I may be wrong about that).

Sometimes a big PR can be very speedily merged - if there has been lengthy discussion in an issue, then there is little point repeating that discussion on the PR. Provided the issue discussion reached a consensus, and the PR implements that consensus, then it should probably be merged speedily.

As @rabernat said, his PR is somewhat controversial, and I should have already commented on it (btw, my excuse is an international flight, and some comments will be forthcoming soon). Given that we haven't reached a consensus, it would be premature to merge that PR.

@mjlosch: "in my current view, it will probably lead to less contributions to the manual than now" - prior to moving to MIT I occasionally found bits of the manual that I wanted to tweak, and had no idea how to do that. As a result I didn't. I'm hopeful that people from outside the core team will feel empowered to create pull requests, and we will see more incremental updates.

Usually one doesn't sign - the post shows clearly who it was written by, and it is generally considered to be part of an ongoing conversation.

**Comment by christophernhill** [comment]
Great - sounds like we are all in some broad sync. Just need to debug details as we go.
